name: Build and Push Guestbook Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend
        run: |
          docker build \
            -t ghcr.io/thesuperswan/guestbook-backend:latest \
            -f guestbook-backend/Dockerfile \
            .
          docker push ghcr.io/thesuperswan/guestbook-backend:latest

      - name: Build and push frontend
        run: |
          docker build \
            -t ghcr.io/thesuperswan/guestbook-frontend:latest \
            -f guestbook-frontend/Dockerfile \
            .
          docker push ghcr.io/thesuperswan/guestbook-frontend:latest
          
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.20"

      - name: Login to OpenShift
        run: |
          oc login \
            -u "${{ secrets.USERNAME }}" \
            -p "${{ secrets.PASSWORD }}" \
            --server="${{ secrets.OCP_SERVER }}" \
            --insecure-skip-tls-verify

      - name: Select project
        run: oc project "${{ secrets.OCP_NAMESPACE }}"

      - name: Deploy to OpenShift
        run: oc apply -f openshift/
